name: PRs on Main

# Defines when the workflow should run
on:
  pull_request_target:
    branches:
      - main
  pull_request_target:
    branches:
      - main

# Jobs to be executed
jobs:
  build:
    runs-on: self-hosted # self Hosted runner

    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.2.0' # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install
      # Installs npm dependencies

    - name: Clean up
      run: npm run clean-up
      # Runs the clean-up script

    - name: Generate TSOA
      run: npm run generate-tsoa
      # Generates TSOA routes and controllers

    - name: Run tests
      run: npm run test
      # Executes your tests

    - name: Pre-build tasks
      run: npm run pre-build
      # Executes pre-build tasks

    - name: Compile TypeScript
      run: npm run compile
      # Runs the TypeScript compiler